spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  liquibase:
    change-log: classpath:/db/changelog/master.xml
    default-schema: liquibase_db

logging:
  level:
    org.springframework.security: trace